### ISSUE TITLE
Word Cluster

### ISSUE THREAD

**Issue by fsrehman** [brendano/ark-tweet-nlp#41]
How to run algorith with word cluster? 
"\n  --word-clusters <File>    Alternate word clusters file (see FeatureExtractor)" +
 Which filename we have to write here?
Thanks in advance

**Comment by brendano** [comment]
You don't need to supply it.  It uses it by default.

**Comment by fsrehman** [comment]
I passed following parameter (--output-format conll   examples/example_tweets.txt). This is the output but i didn't see any word cluster
I	O	0.9983
predict	V	0.9996
I	O	0.9981
won't	V	0.9981
win	V	0.9993
a	D	0.9987
single	A	0.9758
game	N	0.9988
I	O	0.9922
bet	V	0.9995
on	P	0.7823
.	,	0.9919
Got	V	0.9884
Cliff	^	0.9926
Lee	^	0.9998
today	N	0.9899
,	,	0.9988
so	P	0.6624
if	P	0.9970
he	O	0.9979
loses	V	0.9996
its	L	0.9865
on	P	0.9871
me	O	0.9986
RT	~	0.9650
@e_one	@	0.9987
:	~	0.9672
Texas	^	0.9989
(	,	0.9681
cont	~	0.9239
)	,	0.9280
http://tl.gd/6meogh	U	0.9973

RT	~	0.9979
@DjBlack_Pearl	@	0.9991
:	~	0.9812
wat	O	0.9477
muhfuckaz	N	0.6367
wearin	V	0.9580
4	P	0.9377
the	D	0.9979
lingerie	N	0.9688
party	N	0.9856
?????	,	0.9957

Wednesday	^	0.9277
27th	A	0.6266
october	^	0.9716
2010	$	0.9896
.	,	0.9956
ã€‹have	V	0.7115
a	D	0.9934
nice	A	0.9991
day	N	0.9977
:)	E	0.9951

RT	~	0.9979
@ddlovato	@	0.9982
:	~	0.9923
@joejonas	@	0.9969
oh	!	0.9980
,	,	0.9945
hey	!	0.9901
THANKS	N	0.8750
jerk	N	0.9679
!	,	0.9991

@thecamion	@	0.9995
I	O	0.9953
like	V	0.9027
monkeys	N	0.9408
,	,	0.9990
but	&	0.9974
I	O	0.9988
still	R	0.9858
hate	V	0.9938
COSTCO	^	0.9530
parking	N	0.7379
lots	N	0.9867
..	,	0.9952

@DDaimaru	@	0.9993
I	O	0.9980
may	V	0.9945
have	V	0.9996
to	P	0.9980
get	V	0.9995
minecraft	^	0.6605
after	P	0.9643
watching	V	0.9913
videos	N	0.9979
of	P	0.9986
it	O	0.9959

RT	~	0.9979
@eye_ee_duh_Esq	@	0.9991
:	~	0.9938
LMBO	!	0.9965
!	,	0.9983
This	D	0.9918
man	N	0.9904
filed	V	0.9713
an	D	0.9861
EMERGENCY	N	0.9715
Motion	N	0.9859
for	P	0.9995
Continuance	N	0.9229
on	P	0.9955
account	N	0.9991
of	P	0.9995
the	D	0.9990
Rangers	^	0.9495
game	N	0.9776
tonight	N	0.8152
!	,	0.9976
Â«	~	0.6824
Wow	!	0.9663
lmao	!	0.9987

RT	~	0.9979
@musicdenver	@	0.9991
:	~	0.9723
Lady	^	0.8590
Gaga	^	0.9986
-	,	0.9363
Bad	A	0.9757
Romance	N	0.9398
http://dld.bz/n6Xv	U	0.9948

RT	~	0.9979
@cheriexamor	@	0.9991
:	~	0.9453
When	R	0.9893
you	O	0.9995
have	V	0.9998
a	D	0.9974
good	A	0.9991
thing	N	0.9994
,	,	0.9934
hold	V	0.9982
it	O	0.9560
,	,	0.9984
squeeze	V	0.9620
it	O	0.9775
,	,	0.9994
never	R	0.9911
let	V	0.9996
it	O	0.9958
go	V	0.9872
.	,	0.9957

Texas	^	0.9984
Rangers	^	0.9582
are	V	0.9913
in	P	0.9947
the	D	0.9990
World	^	0.8136
Series	^	0.8281
!	,	0.9896
Go	V	0.9870
Rangers	^	0.9551
!!!!!!!!!	,	0.9882

**Comment by brendano** [comment]
The software doesn't have the capability to output word clusters.  Please download the clusters file separately from the webpage if you would like to use it yourself.
